### ISSUE TITLE
06 "undefined method `each' for nil:NilClass (NoMethodError)"

### ISSUE THREAD

**Issue by olwend** [makersacademy/student-directory#18]
Feel really stupid here.... my direct copy from 06 keeps producing this error.
I've added a line to check hash 'students' is created and .length method works. 
I've tried varying e.g. ```name: cohort:```  instead of the given ```:name :cohort```

I've seen this error means I am calling a method that doesn't exist for this class... 

Do I have to change this to use each
```{|key,value|, block} _> hsh``` as per RubyDoc?

SUGGESTIONS PLEASE? 

```def print(students)
  students.each do |student|
    puts "#{student[:name]} (#{student[:cohort]} cohort)"
  end
end

Olwens-MBP:student-directory DOE$ ruby directory.rb
The hash is created - contains 11 students
The students of Villains Academy
-------------
directory.rb:29:in `print': undefined method `each' for nil:NilClass (NoMethodError)
	from directory.rb:38:in `<main>' ```

**Comment by olwend** [comment]
```
students = [
  {name: "Dr. Hannibal Lecter", cohort: :november},
  {name: "Darth Vader", cohort: :november},
  {name: "Nurse Ratched", cohort: :november},
  {name: "Michael Corleone", cohort: :november},
  {name: "Alex DeLarge", cohort: :november},
  {name: "The Wicked Witch of the West", cohort: :november},
  {name: "Terminator", cohort: :november},
  {name: "Freddy Krueger", cohort: :november},
  {name: "The Joker", cohort: :november},
  {name: "Joffrey Baratheon", cohort: :november},
  {name: "Norman Bates", cohort: :november}
]

```
